import time
import logging
import win32evtlog # Interacts with Windows Event Viewer
import xml.etree.ElementTree as ET
from collections import defaultdict
from datetime import datetime

logging.basicConfig(level=logging.WARNING, format="%(asctime)s - %(message)s")
logger = logging.getLogger("QNNX_HIDS")

class WindowsHIDSAlertEngine:
    def __init__(self):
        # --- State Tracking ---
        self.auth_fails = defaultdict(list)
        # IDS Port Scan Tracker: {ip_address: {port1, port2, port3}}
        self.port_scan_tracker = defaultdict(set)
        self.port_scan_timestamps = defaultdict(list)

        # --- Thresholds & Rules ---
        self.AUTH_FAIL_LIMIT = 5
        self.AUTH_FAIL_WINDOW = 600  # 10 minutes
        
        self.IDS_PORT_SCAN_LIMIT = 15 # Hits to 15 unique ports
        self.IDS_SCAN_WINDOW = 60     # Within 60 seconds
        self.vpn_peers = {}
        # --- Whitelists ---
        # IPs your backend is ALLOWED to connect to (e.g., PostgreSQL, Redis, external APIs)
        self.ALLOWED_OUTBOUND_IPS = {"127.0.0.1", "192.168.1.100", "8.8.8.8"}
        # The explicit path to your web server executable
        self.APPROVED_PARENT_PROCESSES = {"python.exe", "uvicorn.exe"}
        # Processes that should NEVER be spawned by your web server
        self.HOSTILE_CHILDREN = {"cmd.exe", "powershell.exe", "bash.exe", "netcat.exe", "curl.exe"}

    def _clean_ids_state(self, ip: str, current_time: float):
        """Cleans old timestamps and ports from the IDS tracker."""
        valid_times = []
        for t in self.port_scan_timestamps[ip]:
            if current_time - t <= self.IDS_SCAN_WINDOW:
                valid_times.append(t)
        
        self.port_scan_timestamps[ip] = valid_times
        if not valid_times:
            self.port_scan_tracker[ip].clear()

    def trigger_alert(self, severity: str, rule: str, ip_address: str, message: str, details: dict = None):
        alert_payload = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "severity": severity,
            "rule": rule,
            "target_ip": ip_address,
            "message": message,
            "details": details or {}
        }
        logger.warning(f"[{severity}] RULE: {rule} | IP: {ip_address} | MSG: {message}")
        # Insert webhook or SIEM forwarder here
        return alert_payload

    # ---------------------------------------------------------
    # NEW: API Layer Security Event Processing
    # ---------------------------------------------------------
    def process_api_event(self, event_type: str, ip_address: str, details: dict = None):
        """Analyzes application-layer security events (Auth Failures & Brute-Force)."""
        current_time = time.time()
        
        # Target the exact event types generated by dependencies.py
        if event_type in ["INVALID_API_KEY", "INVALID_SIGNATURE", "MISSING_HEADERS", "REPLAY_ATTACK", "EXPIRED_REQUEST"]:
            
            # Clean old attempts outside the 10-minute window
            valid_times = [t for t in self.auth_fails[ip_address] if current_time - t <= self.AUTH_FAIL_WINDOW]
            self.auth_fails[ip_address] = valid_times
            
            # Log the new failure
            self.auth_fails[ip_address].append(current_time)

            # Trigger alert if threshold is breached
            if len(self.auth_fails[ip_address]) >= self.AUTH_FAIL_LIMIT:
                self.trigger_alert(
                    severity="HIGH",
                    rule="BRUTE_FORCE_AUTH",
                    ip_address=ip_address,
                    message=f"Excessive API auth failures ({self.AUTH_FAIL_LIMIT}+ in 10 mins).",
                    details=details
                )
                self.auth_fails[ip_address].clear() # Reset to prevent alert spam

    # ---------------------------------------------------------
    # Windows Host Layer Security Event Processing
    # ---------------------------------------------------------
    def process_windows_event(self, event_id: int, event_data: dict):
        """Analyzes structured Windows Sysmon data against IDS rules."""
        current_time = time.time()

        # 1. Suspicious Process Execution (Sysmon Event ID 1)
        if event_id == 1:
            parent_image = event_data.get("ParentImage", "").lower()
            child_image = event_data.get("Image", "").lower()
            
            # Check if our Python backend is spawning something it shouldn't
            if any(p in parent_image for p in self.APPROVED_PARENT_PROCESSES):
                if any(h in child_image for h in self.HOSTILE_CHILDREN):
                    self.trigger_alert(
                        severity="CRITICAL",
                        rule="RCE_DETECTED",
                        ip_address="localhost",
                        message=f"Web server spawned hostile shell: {child_image}",
                        details=event_data
                    )
            return

        # 2. Network Telemetry (Sysmon Event ID 3)
        if event_id == 3:
            direction = "outbound" if event_data.get("Initiated") == "true" else "inbound"
            src_ip = event_data.get("SourceIp", "")
            dst_ip = event_data.get("DestinationIp", "")
            dst_port = event_data.get("DestinationPort", "")
            process = event_data.get("Image", "").lower()

            # --- Rule A: Unusual Outbound Connections ---
            if direction == "outbound" and any(p in process for p in self.APPROVED_PARENT_PROCESSES):
                if dst_ip not in self.ALLOWED_OUTBOUND_IPS:
                    self.trigger_alert(
                        severity="CRITICAL",
                        rule="UNAUTHORIZED_OUTBOUND_C2",
                        ip_address=dst_ip,
                        message=f"Backend process initiated unwhitelisted connection to {dst_ip}:{dst_port}",
                        details=event_data
                    )

            # --- Rule B: IDS Port Scanning (Vertical Scan Logic) ---
            if direction == "inbound":
                self._clean_ids_state(src_ip, current_time)
                
                self.port_scan_timestamps[src_ip].append(current_time)
                self.port_scan_tracker[src_ip].add(dst_port)

                # IDS Trigger: If 1 IP hits more than X unique ports within the time window
                if len(self.port_scan_tracker[src_ip]) >= self.IDS_PORT_SCAN_LIMIT:
                    self.trigger_alert(
                        severity="MEDIUM",
                        rule="IDS_VERTICAL_PORT_SCAN",
                        ip_address=src_ip,
                        message=f"Port scan detected. {len(self.port_scan_tracker[src_ip])} unique ports targeted.",
                        details={"scanned_ports": list(self.port_scan_tracker[src_ip])}
                    )
                    # Reset to prevent alert flooding
                    self.port_scan_tracker[src_ip].clear()
                    self.port_scan_timestamps[src_ip].clear()
            return
    

    # ---------------------------------------------------------
    # NEW: VPN Layer Security Event Processing
    # ---------------------------------------------------------
    def process_vpn_event(self, event_type: str, peer_id: str, ip_address: str = None, details: dict = None):
        """Analyzes stateful VPN events including tunnel health and endpoint roaming."""
        
        # Register the peer if it is their first time connecting
        if peer_id not in self.vpn_peers:
            self.vpn_peers[peer_id] = {"last_ip": ip_address, "status": "unknown"}

        # --- 1. Tunnel Failure & Heartbeat Loss ---
        if event_type in ["TUNNEL_DOWN", "HEARTBEAT_LOSS"]:
            # Only alert if the tunnel was previously known to be "up" to avoid spamming
            if self.vpn_peers[peer_id]["status"] == "up":
                self.trigger_alert(
                    severity="HIGH",
                    rule="VPN_TUNNEL_FAILURE",
                    ip_address=ip_address or self.vpn_peers[peer_id]["last_ip"],
                    message=f"VPN connection lost for peer: {peer_id} ({event_type})",
                    details=details
                )
            self.vpn_peers[peer_id]["status"] = "down"

        # --- 2. Endpoint IP Change (Roaming or Spoofing) ---
        elif event_type == "ENDPOINT_IP_CHANGE":
            old_ip = self.vpn_peers[peer_id].get("last_ip")
            
            # Alert if the IP has changed during an active or returning session
            if old_ip and old_ip != ip_address and ip_address is not None:
                self.trigger_alert(
                    severity="MEDIUM",
                    rule="VPN_IP_CHANGE",
                    ip_address=ip_address,
                    message=f"VPN peer {peer_id} unexpectedly changed IP from {old_ip} to {ip_address}",
                    details={"old_ip": old_ip, "new_ip": ip_address, **(details or {})}
                )
            self.vpn_peers[peer_id]["last_ip"] = ip_address

        # --- 3. Tunnel Establishment / Recovery ---
        elif event_type == "TUNNEL_UP":
            self.vpn_peers[peer_id]["status"] = "up"
            self.vpn_peers[peer_id]["last_ip"] = ip_address
    
    def process_hardware_event(self, event_type: str, device_name: str = "Unknown", details: dict = None):
        """Analyzes physical hardware events like USB insertions."""
        
        if event_type == "USB_INSERTION":
            self.trigger_alert(
                severity="CRITICAL",
                rule="UNAUTHORIZED_USB_INSERTION",
                ip_address="localhost",  # Physical events happen locally
                message=f"Unauthorized USB mass storage device connected: {device_name}",
                details=details
            )
# Initialize Engine
hids_engine = WindowsHIDSAlertEngine()